name: CI

on: 
  push:
    branches: 
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpunit:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    container: 
      image: klinktechnology/k-box-ci-pipeline-php:${{ matrix.php }}
      options: --user root 

    strategy:
      fail-fast: true
      matrix:
        php: [8.3]
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
   
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: /home/php/.composer/cache
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Cache JS dependencies
      uses: actions/cache@v4
      with:
        path: ~/.yarn/
        key: dependencies-js-${{ matrix.php }}-yarn-${{ hashFiles('yarn.lock') }}
      
    - name: Prepare environment
      run: |
        rm -f /usr/local/etc/php/conf.d/docker-php-ext-pcov.ini
        composer install --prefer-dist
        yarn config set cache-folder ~/.yarn/
        yarn
        yarn build
        
    - name: Run Testsuite
      run: |
        echo "APP_KEY=" > .env
        php artisan key:generate
        php artisan view:clear
        php artisan config:clear
        php artisan route:clear
        vendor/bin/phpunit
